import { FaUtensils, FaStore, FaCapsules } from 'react-icons/fa';
import { GiCarWheel, GiTyre } from 'react-icons/gi';
import { MdTableRestaurant, MdMedication, MdInventory2 } from 'react-icons/md';

export const BUSINESS_CONFIG = {
  tyre_shop: {
    label: 'Tyre Shop',
    icon: GiCarWheel,
    color: '#f97316',
    inventoryLabel: 'Inventory',
    inventoryIcon: GiTyre,
    itemLabel: 'Tyre',
    itemsLabel: 'Tyres',
    salesLabel: 'Sales / POS',
    suppliersLabel: 'Suppliers',
    showTables: false,
    itemFields: [
      { key: 'brand',               label: 'Brand',            type: 'text',   required: true,  placeholder: 'e.g. Michelin' },
      { key: 'model',               label: 'Model',            type: 'text',   required: true,  placeholder: 'e.g. Primacy 4' },
      { key: 'size',                label: 'Size',             type: 'text',   required: true,  placeholder: '225/50 R17' },
      { key: 'type',                label: 'Type',             type: 'select', required: false, options: ['Passenger','SUV','Truck'] },
      { key: 'price',               label: 'Price (Rs.)',      type: 'number', required: true },
      { key: 'stock',               label: 'Stock Qty',        type: 'number', required: false },
      { key: 'low_stock_threshold', label: 'Low Stock Alert',  type: 'number', required: false },
      { key: 'barcode',             label: 'Barcode',          type: 'text',   required: false, placeholder: 'Optional' },
    ],
    itemName: (item) => `${item.brand} ${item.model} ${item.size}`,
    itemSubtitle: (item) => item.type,
    filterOptions: ['All', 'Passenger', 'SUV', 'Truck'],
    filterKey: 'type',
    emptyDefaults: { brand:'', model:'', size:'', type:'Passenger', price:'', stock:'', low_stock_threshold:10, barcode:'' },
  },

  restaurant: {
    label: 'Restaurant',
    icon: FaUtensils,
    color: '#f97316',
    inventoryLabel: 'Menu',
    inventoryIcon: MdTableRestaurant,
    itemLabel: 'Menu Item',
    itemsLabel: 'Menu Items',
    salesLabel: 'Orders / POS',
    suppliersLabel: 'Suppliers',
    showTables: true,
    itemFields: [
      { key: 'name',                label: 'Item Name',        type: 'text',   required: true,  placeholder: 'e.g. Chicken Burger' },
      { key: 'category',            label: 'Category',         type: 'select', required: false, options: ['Starters','Main Course','Drinks','Desserts','Snacks','Other'] },
      { key: 'price',               label: 'Price (Rs.)',      type: 'number', required: true },
      { key: 'stock',               label: 'Available Qty',    type: 'number', required: false },
      { key: 'low_stock_threshold', label: 'Low Stock Alert',  type: 'number', required: false },
      { key: 'available',           label: 'Available',        type: 'select', required: false, options: ['1','0'], optionLabels: ['Yes','No'] },
    ],
    itemName: (item) => item.name,
    itemSubtitle: (item) => item.category,
    filterOptions: ['All', 'Starters', 'Main Course', 'Drinks', 'Desserts', 'Snacks'],
    filterKey: 'category',
    emptyDefaults: { name:'', category:'Main Course', price:'', stock:'', low_stock_threshold:5, available:'1' },
  },

  general_store: {
    label: 'General Store',
    icon: FaStore,
    color: '#f97316',
    inventoryLabel: 'Products',
    inventoryIcon: MdInventory2,
    itemLabel: 'Product',
    itemsLabel: 'Products',
    salesLabel: 'Sales / POS',
    suppliersLabel: 'Suppliers',
    showTables: false,
    itemFields: [
      { key: 'name',                label: 'Product Name',     type: 'text',   required: true,  placeholder: 'e.g. Surf Excel 1kg' },
      { key: 'brand',               label: 'Brand',            type: 'text',   required: false, placeholder: 'e.g. Unilever' },
      { key: 'category',            label: 'Category',         type: 'select', required: false, options: ['Grocery','Beverages','Dairy','Snacks','Cleaning','Personal Care','Other'] },
      { key: 'barcode',             label: 'Barcode',          type: 'text',   required: false, placeholder: 'Optional' },
      { key: 'price',               label: 'Sale Price (Rs.)', type: 'number', required: true },
      { key: 'cost',                label: 'Cost Price (Rs.)', type: 'number', required: false },
      { key: 'stock',               label: 'Stock Qty',        type: 'number', required: false },
      { key: 'low_stock_threshold', label: 'Low Stock Alert',  type: 'number', required: false },
    ],
    itemName: (item) => item.name,
    itemSubtitle: (item) => item.brand || item.category,
    filterOptions: ['All', 'Grocery', 'Beverages', 'Dairy', 'Snacks', 'Cleaning', 'Personal Care'],
    filterKey: 'category',
    emptyDefaults: { name:'', brand:'', category:'Grocery', barcode:'', price:'', cost:'', stock:'', low_stock_threshold:5 },
  },

  pharmacy: {
    label: 'Pharmacy',
    icon: FaCapsules,
    color: '#f97316',
    inventoryLabel: 'Medicines',
    inventoryIcon: MdMedication,
    itemLabel: 'Medicine',
    itemsLabel: 'Medicines',
    salesLabel: 'Sales / POS',
    suppliersLabel: 'Suppliers',
    showTables: false,
    itemFields: [
      { key: 'name',                label: 'Medicine Name',    type: 'text',   required: true,  placeholder: 'e.g. Panadol 500mg' },
      { key: 'generic_name',        label: 'Generic Name',     type: 'text',   required: false, placeholder: 'e.g. Paracetamol' },
      { key: 'company',             label: 'Company',          type: 'text',   required: false, placeholder: 'e.g. GSK' },
      { key: 'category',            label: 'Category',         type: 'select', required: false, options: ['Tablet','Syrup','Injection','Capsule','Cream','Drops','Other'] },
      { key: 'barcode',             label: 'Barcode',          type: 'text',   required: false, placeholder: 'Optional' },
      { key: 'price',               label: 'Sale Price (Rs.)', type: 'number', required: true },
      { key: 'cost',                label: 'Cost Price (Rs.)', type: 'number', required: false },
      { key: 'stock',               label: 'Stock Qty',        type: 'number', required: false },
      { key: 'low_stock_threshold', label: 'Low Stock Alert',  type: 'number', required: false },
      { key: 'expiry_date',         label: 'Expiry Date',      type: 'date',   required: false },
    ],
    itemName: (item) => item.name,
    itemSubtitle: (item) => item.generic_name || item.company,
    filterOptions: ['All', 'Tablet', 'Syrup', 'Injection', 'Capsule', 'Cream', 'Drops'],
    filterKey: 'category',
    emptyDefaults: { name:'', generic_name:'', company:'', category:'Tablet', barcode:'', price:'', cost:'', stock:'', low_stock_threshold:10, expiry_date:'' },
  },
};

export const getConfig = (businessType) => BUSINESS_CONFIG[businessType] || BUSINESS_CONFIG.general_store;
